export const fakeroles = [
  {
    _id: "1",
    name: "Super Admin",
    enabled: true,
    moduleAccess: [
      {
        _id: "m1",
        name: "CRM Dashboard",
        enabled: true,
        permissions: ["View"],
      },
      {
        _id: "m2",
        name: "CRM Leads",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m3",
        name: "CRM Tasks",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m4",
        name: "CRM Support",
        enabled: true,
        permissions: ["View", "Edit"],
      },
      {
        _id: "m5",
        name: "CRM Leaderboard",
        enabled: true,
        permissions: ["View", "Create"],
      },
      {
        _id: "m6",
        name: "CRM Representatives",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m7",
        name: "Store Dashboard",
        enabled: true,
        permissions: ["View"],
      },
      {
        _id: "m8",
        name: "Store Products",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m9",
        name: "Store Categories",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m10",
        name: "Store Orders",
        enabled: true,
        permissions: ["View", "Edit", "Delete"],
      },
      {
        _id: "m11",
        name: "Category",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m12",
        name: "Curriculum",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m13",
        name: "Course",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m14",
        name: "Live Class",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m15",
        name: "Live Exam",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m16",
        name: "Question Bank",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m17",
        name: "Question Set",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m18",
        name: "Enrollment",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m19",
        name: "Manage Student",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m20",
        name: "Manage Promotion",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m21",
        name: "Bundle Course",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m22",
        name: "Coupon",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m23",
        name: "SMS & Email",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m24",
        name: "Job Portal",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m25",
        name: "Case Study",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m26",
        name: "Manage Mentor",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m27",
        name: "Manage Website",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
    ],
  },
  {
    _id: "2",
    name: "Content Manager",
    enabled: true,
    moduleAccess: [
      {
        _id: "m11",
        name: "Category",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m12",
        name: "Curriculum",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m13",
        name: "Course",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m14",
        name: "Live Class",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m15",
        name: "Live Exam",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m16",
        name: "Question Bank",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m17",
        name: "Question Set",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m27",
        name: "Manage Website",
        enabled: true,
        permissions: ["View", "Edit"],
      },
    ],
  },
  {
    _id: "3",
    name: "CRM Manager",
    enabled: true,
    moduleAccess: [
      {
        _id: "m1",
        name: "CRM Dashboard",
        enabled: true,
        permissions: ["View"],
      },
      {
        _id: "m2",
        name: "CRM Leads",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m3",
        name: "CRM Tasks",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
      {
        _id: "m4",
        name: "CRM Support",
        enabled: true,
        permissions: ["View", "Edit"],
      },
      {
        _id: "m5",
        name: "CRM Leaderboard",
        enabled: true,
        permissions: ["View", "Create"],
      },
      {
        _id: "m6",
        name: "CRM Representatives",
        enabled: true,
        permissions: ["View", "Edit", "Delete", "Create"],
      },
    ],
  },
];

export const fakeemployees = [
  {
    _id: "e1",
    name: "John Doe",
    email: "john@example.com",
    enabled: true,
    roleId: "1",
    customAccess: [],
  },
  {
    _id: "e2",
    name: "Jane Smith",
    email: "jane@example.com",
    enabled: true,
    roleId: "2",
    customAccess: [
      { moduleId: "m27", permissions: ["View", "Edit", "Delete"] },
    ],
  },
  {
    _id: "e3",
    name: "Mike Johnson",
    email: "mike@example.com",
    enabled: true,
    roleId: "3",
    customAccess: [
      { moduleId: "m2", permissions: ["View", "Edit"] },
      { moduleId: "m6", permissions: ["View"] },
    ],
  },
];
